-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 16:27:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DZ3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DZ3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DZ3` DEFAULT CHARACTER SET utf8 ;
USE `DZ3` ;

-- -----------------------------------------------------
-- Table `DZ3`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Teachers` (
  `id` INT NOT NULL,
  `EmploymentDate` DATE NOT NULL COMMENT 'Дата трудоустройства ',
  `IsAssistant` BIT(8) NOT NULL DEFAULT '0',
  `IsProfessor` BIT(8) NOT NULL DEFAULT '0',
  `Name` NVARCHAR(1000) NOT NULL,
  `Position` NVARCHAR(1000) NOT NULL,
  `Premium` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'п',
  `Salary` INT UNSIGNED NOT NULL COMMENT 'о',
  `Surname` NVARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Groups` (
  `id` INT NOT NULL,
  `Name` NVARCHAR(10) NOT NULL,
  `Raiting` INT(6) UNSIGNED NOT NULL DEFAULT '0',
  `Year` INT(5) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Название (Name)_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Faculties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Dean` NVARCHAR(1000) NOT NULL COMMENT 'Декан',
  `Name` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Название (Name)_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Financing` INT UNSIGNED NOT NULL DEFAULT '0',
  `Name` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Название (Name)_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Academy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Academy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTeachers` INT NOT NULL,
  `idGroups` INT NOT NULL,
  `idFaculties` INT NOT NULL,
  `idDepartments` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Teachers_idx` (`idTeachers` ASC) VISIBLE,
  INDEX `Groups_idx` (`idGroups` ASC) VISIBLE,
  INDEX `Faculties_idx` (`idFaculties` ASC) VISIBLE,
  INDEX `Departments_idx` (`idDepartments` ASC) VISIBLE,
  CONSTRAINT `Teachers`
    FOREIGN KEY (`idTeachers`)
    REFERENCES `DZ3`.`Teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Groups`
    FOREIGN KEY (`idGroups`)
    REFERENCES `DZ3`.`Groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Faculties`
    FOREIGN KEY (`idFaculties`)
    REFERENCES `DZ3`.`Faculties` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Departments`
    FOREIGN KEY (`idDepartments`)
    REFERENCES `DZ3`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
