-- MySQL Script generated by MySQL Workbench
-- Sat Jan 25 19:26:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DZ3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DZ3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DZ3` DEFAULT CHARACTER SET utf8 ;
USE `DZ3` ;

-- -----------------------------------------------------
-- Table `DZ3`.`Преподаватели (Teachers)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Преподаватели (Teachers)` (
  `id` INT NOT NULL,
  `Дата трудоустройства (EmploymentDate)` DATE NOT NULL,
  `Ассистент (IsAssistant)` BIT(8) NOT NULL DEFAULT '0',
  `Профессор (IsProfessor)` BIT(8) NOT NULL DEFAULT '0',
  `Имя (Name)` NVARCHAR(1000) NOT NULL,
  `Должность (Position)` NVARCHAR(1000) NOT NULL,
  `Надбавка (Premium)` INT UNSIGNED NOT NULL DEFAULT '0',
  `Ставка (Salary)` INT UNSIGNED NOT NULL,
  `Фамилия (Surname)` NVARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Группы (Groups)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Группы (Groups)` (
  `id` INT NOT NULL,
  `Название (Name)` NVARCHAR(10) NOT NULL,
  `Рейтинг (Raiting)` INT(6) UNSIGNED NOT NULL DEFAULT '0',
  `Курс (Year)` INT(5) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Название (Name)_UNIQUE` (`Название (Name)` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Факультеты (Faculties)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Факультеты (Faculties)` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Декан (Dean)` NVARCHAR(1000) NOT NULL,
  `Название (Name)` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Название (Name)_UNIQUE` (`Название (Name)` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Кафедры (Departments)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Кафедры (Departments)` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Финансирование (Financing)` INT UNSIGNED NOT NULL DEFAULT '0',
  `Название (Name)` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Название (Name)_UNIQUE` (`Название (Name)` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DZ3`.`Академия (Academy)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DZ3`.`Академия (Academy)` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTeachers` INT NOT NULL,
  `idGroups` INT NOT NULL,
  `idFaculties` INT NOT NULL,
  `idDepartments` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Teachers_idx` (`idTeachers` ASC) VISIBLE,
  INDEX `Groups_idx` (`idGroups` ASC) VISIBLE,
  INDEX `Faculties_idx` (`idFaculties` ASC) VISIBLE,
  INDEX `Departments_idx` (`idDepartments` ASC) VISIBLE,
  CONSTRAINT `Teachers`
    FOREIGN KEY (`idTeachers`)
    REFERENCES `DZ3`.`Преподаватели (Teachers)` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Groups`
    FOREIGN KEY (`idGroups`)
    REFERENCES `DZ3`.`Группы (Groups)` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Faculties`
    FOREIGN KEY (`idFaculties`)
    REFERENCES `DZ3`.`Факультеты (Faculties)` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Departments`
    FOREIGN KEY (`idDepartments`)
    REFERENCES `DZ3`.`Кафедры (Departments)` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
